FROM tensorflow/tensorflow

RUN apt-get update -y
RUN apt-get upgrade -y

RUN apt-get install -y build-essential cmake unzip pkg-config
RUN apt-get install -y libxmu-dev libxi-dev libglu1-mesa libglu1-mesa-dev
RUN apt-get install -y libjpeg-dev libpng-dev libtiff-dev
RUN apt-get install -y libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
RUN apt-get install -y libxvidcore-dev libx264-dev
RUN apt-get install -y libgtk-3-dev
RUN apt-get install -y libopenblas-dev libatlas-base-dev liblapack-dev gfortran
RUN apt-get install -y libhdf5-serial-dev
RUN apt-get install -y python3-dev 

RUN pip3 install scipy matplotlib pillow
RUN pip3 install imutils h5py requests progressbar2
RUN pip3 install scikit-learn scikit-image
RUN pip3 install keras
