FROM centos:8

RUN dnf update -y
RUN dnf install -y tmux vim python3 python2

RUN pip2 install theano
RUN pip2 install keras

RUN dnf groupinstall -y "Development Tools"
#RUN dnf install -y python2-devel.x86_64
#RUN pip2 install tensorflow
RUN dnf install -y python3-devel
RUN pip3 install tensorflow

WORKDIR /HW1
